FROM mcr.microsoft.com/dotnet/sdk:5.0
ENV ASPNETCORE_URLS=http://+:5000
#ENV DOTNET_USE_POLLING_FILE_WATCHER 1
EXPOSE 5000

WORKDIR /app

COPY *.csproj .
RUN dotnet restore

COPY . .
RUN dotnet build

CMD [ "dotnet", "watch", "run", "--no-launch-profile", "-c", "Debug" ]
#WORKDIR /app/bin/Debug/net5.0
#ENTRYPOINT [ "dotnet", "server.dll" ]


# para produccion
#FROM mcr.microsoft.com/dotnet/sdk:5.0 as build-env
#WORKDIR /app
#
#COPY *.csproj .
#RUN dotnet restore


#COPY . .
#RUN dotnet publish -c Release -o out
#FROM mcr.microsoft.com/dotnet/aspnet:5.0
#ENV ASPNETCORE_URLS=http://+:5000  
#EXPOSE 5000
#WORKDIR /app
#COPY --from=build-env /app/out .
#ENTRYPOINT [ "dotnet", "server.dll" ]

