FROM mcr.microsoft.com/dotnet/sdk:3.1

WORKDIR /app

COPY *.csproj .
RUN dotnet restore

COPY . .
RUN dotnet build

CMD [ "dotnet", "watch", "run", "--no-launch-profile", "-c", "Debug" ]

#FROM mcr.microsoft.com/dotnet/sdk:5.0 as build-env
#WORKDIR /app#

#COPY *.csproj .
#RUN dotnet restore#

#COPY . .
#RUN dotnet publish -c Release -o out#

#FROM mcr.microsoft.com/dotnet/sdk:3.1
#WORKDIR /app
#COPY --from=build-env /app/out .
#ENTRYPOINT [ "dotnet", "worker.dll" ]